#!/bin/zsh

if [ -z "$1" ]
then
    docker rmi -f $(docker images --format "{{.Repository}}:{{.Tag}}" | grep -v "<none>") 

else
    docker rmi -f $(docker images --format "{{.Repository}}:{{.Tag}}" | grep $1)
fi
